<?xml version="1.0" encoding="utf-8"?><Database Name="WFS_ERP" Class="LinqDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=116.202.193.203,1232;Initial Catalog=WFS_ERP;User ID=wfsuser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DbConStr" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MstCourse" Member="MstCourses">
    <Type Name="MstCourse">
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsTeam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstCourse_Tbl_TrnSchedule" Member="Tbl_TrnSchedules" ThisKey="CourseId" OtherKey="CourseId" Type="Tbl_TrnSchedule" />
      <Association Name="MstCourse_Tbl_TrnSchedule1" Member="Tbl_TrnSchedules1" ThisKey="CourseId" OtherKey="CourseId" Type="Tbl_TrnSchedule" />
      <Association Name="MstCourse_MstCourseFee" Member="MstCourseFees" ThisKey="CourseId" OtherKey="CourseId" Type="MstCourseFee" />
      <Association Name="MstCourse_Tbl_Enquiry" Member="Tbl_Enquiries" ThisKey="CourseId" OtherKey="CourseId" Type="Tbl_Enquiry" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_CoachEvents" Member="Tbl_CoachEvents">
    <Type Name="Tbl_CoachEvent">
      <Column Name="CEvntId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CoachId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstUsers" Member="MstUsers">
    <Type Name="MstUser">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ManagerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IpCode" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UTCOffset" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstUserType" Member="MstUserTypes">
    <Type Name="MstUserType">
      <Column Name="UserTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_FeeDetail" Member="Tbl_FeeDetails">
    <Type Name="Tbl_FeeDetail">
      <Column Name="FDetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CFeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeeTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FeeAmount" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstFeeType_Tbl_FeeDetail" Member="MstFeeType" ThisKey="FeeTypeId" OtherKey="FeeTypeId" Type="MstFeeType" IsForeignKey="true" />
      <Association Name="MstFeeType_Tbl_FeeDetail1" Member="MstFeeType1" ThisKey="FeeTypeId" OtherKey="FeeTypeId" Type="MstFeeType" IsForeignKey="true" />
      <Association Name="MstFeeType_Tbl_FeeDetail2" Member="MstFeeType2" ThisKey="FeeTypeId" OtherKey="FeeTypeId" Type="MstFeeType" IsForeignKey="true" />
      <Association Name="MstCourseFee_Tbl_FeeDetail" Member="MstCourseFee" ThisKey="CFeeId" OtherKey="CFeeId" Type="MstCourseFee" IsForeignKey="true" />
      <Association Name="MstCourseFee_Tbl_FeeDetail1" Member="MstCourseFee1" ThisKey="CFeeId" OtherKey="CFeeId" Type="MstCourseFee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_TrnSchedule" Member="Tbl_TrnSchedules">
    <Type Name="Tbl_TrnSchedule">
      <Column Name="TSchdlId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ScheduleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrainerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ClassDays" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FromTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ToTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Tbl_TrnSchedule_MstCourseFee" Member="MstCourseFees" ThisKey="TSchdlId" OtherKey="TSchdlId" Type="MstCourseFee" />
      <Association Name="Tbl_TrnSchedule_Tbl_Enquiry" Member="Tbl_Enquiries" ThisKey="TSchdlId" OtherKey="TSchdlId" Type="Tbl_Enquiry" />
      <Association Name="MstCourse_Tbl_TrnSchedule" Member="MstCourse" ThisKey="CourseId" OtherKey="CourseId" Type="MstCourse" IsForeignKey="true" />
      <Association Name="MstCourse_Tbl_TrnSchedule1" Member="MstCourse1" ThisKey="CourseId" OtherKey="CourseId" Type="MstCourse" IsForeignKey="true" />
      <Association Name="MstLocation_Tbl_TrnSchedule" Member="MstLocation" ThisKey="LocationId" OtherKey="LocId" Type="MstLocation" IsForeignKey="true" />
      <Association Name="MstTrainer_Tbl_TrnSchedule" Member="MstTrainer" ThisKey="TrainerId" OtherKey="TrainerId" Type="MstTrainer" IsForeignKey="true" />
      <Association Name="MstTrainer_Tbl_TrnSchedule1" Member="MstTrainer1" ThisKey="TrainerId" OtherKey="TrainerId" Type="MstTrainer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstLocation" Member="MstLocations">
    <Type Name="MstLocation">
      <Column Name="LocId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LocAddress" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstLocation_Tbl_TrnSchedule" Member="Tbl_TrnSchedules" ThisKey="LocId" OtherKey="LocationId" Type="Tbl_TrnSchedule" />
    </Type>
  </Table>
  <Table Name="dbo.MstTrainer" Member="MstTrainers">
    <Type Name="MstTrainer">
      <Column Name="TrainerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstTrainer_Tbl_TrnSchedule" Member="Tbl_TrnSchedules" ThisKey="TrainerId" OtherKey="TrainerId" Type="Tbl_TrnSchedule" />
      <Association Name="MstTrainer_Tbl_TrnSchedule1" Member="Tbl_TrnSchedules1" ThisKey="TrainerId" OtherKey="TrainerId" Type="Tbl_TrnSchedule" />
      <Association Name="MstTrainer_Tbl_TrainerCourse" Member="Tbl_TrainerCourses" ThisKey="TrainerId" OtherKey="TrainerId" Type="Tbl_TrainerCourse" />
      <Association Name="MstTrainer_Tbl_TrainerCourse1" Member="Tbl_TrainerCourses1" ThisKey="TrainerId" OtherKey="TrainerId" Type="Tbl_TrainerCourse" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_TrainerCourses" Member="Tbl_TrainerCourses">
    <Type Name="Tbl_TrainerCourse">
      <Column Name="CEvntId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TrainerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstTrainer_Tbl_TrainerCourse" Member="MstTrainer" ThisKey="TrainerId" OtherKey="TrainerId" Type="MstTrainer" IsForeignKey="true" />
      <Association Name="MstTrainer_Tbl_TrainerCourse1" Member="MstTrainer1" ThisKey="TrainerId" OtherKey="TrainerId" Type="MstTrainer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstFeeType" Member="MstFeeTypes">
    <Type Name="MstFeeType">
      <Column Name="FeeTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FeeType" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="MstFeeType_Tbl_FeeDetail" Member="Tbl_FeeDetails" ThisKey="FeeTypeId" OtherKey="FeeTypeId" Type="Tbl_FeeDetail" />
      <Association Name="MstFeeType_Tbl_FeeDetail1" Member="Tbl_FeeDetails1" ThisKey="FeeTypeId" OtherKey="FeeTypeId" Type="Tbl_FeeDetail" />
      <Association Name="MstFeeType_Tbl_FeeDetail2" Member="Tbl_FeeDetails2" ThisKey="FeeTypeId" OtherKey="FeeTypeId" Type="Tbl_FeeDetail" />
    </Type>
  </Table>
  <Table Name="dbo.MstCourseFee" Member="MstCourseFees">
    <Type Name="MstCourseFee">
      <Column Name="CFeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TSchdlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstCourseFee_Tbl_FeeDetail" Member="Tbl_FeeDetails" ThisKey="CFeeId" OtherKey="CFeeId" Type="Tbl_FeeDetail" />
      <Association Name="MstCourseFee_Tbl_FeeDetail1" Member="Tbl_FeeDetails1" ThisKey="CFeeId" OtherKey="CFeeId" Type="Tbl_FeeDetail" />
      <Association Name="MstCourseFee_Tbl_Enquiry" Member="Tbl_Enquiries" ThisKey="CFeeId" OtherKey="CFeeId" Type="Tbl_Enquiry" />
      <Association Name="MstCourse_MstCourseFee" Member="MstCourse" ThisKey="CourseId" OtherKey="CourseId" Type="MstCourse" IsForeignKey="true" />
      <Association Name="Tbl_TrnSchedule_MstCourseFee" Member="Tbl_TrnSchedule" ThisKey="TSchdlId" OtherKey="TSchdlId" Type="Tbl_TrnSchedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Enquiry" Member="Tbl_Enquiries">
    <Type Name="Tbl_Enquiry">
      <Column Name="EnqId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnqDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StudId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TSchdlId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignedTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnqStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CFeeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnrolledOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StudentId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MstCourse_Tbl_Enquiry" Member="MstCourse" ThisKey="CourseId" OtherKey="CourseId" Type="MstCourse" IsForeignKey="true" />
      <Association Name="MstCourseFee_Tbl_Enquiry" Member="MstCourseFee" ThisKey="CFeeId" OtherKey="CFeeId" Type="MstCourseFee" IsForeignKey="true" />
      <Association Name="Tbl_TrnSchedule_Tbl_Enquiry" Member="Tbl_TrnSchedule" ThisKey="TSchdlId" OtherKey="TSchdlId" Type="Tbl_TrnSchedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstStudent" Member="MstStudents">
    <Type Name="MstStudent">
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="StudentId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UniqueId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Imagepath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UAEId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Sibling" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SibId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnqId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstEnqSource" Member="MstEnqSources">
    <Type Name="MstEnqSource">
      <Column Name="EnqSrcId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SourceName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MstEnquiry" Member="MstEnquiries">
    <Type Name="MstEnquiry">
      <Column Name="EnqId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EnqDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EnqType" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssignTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnqSrcId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnqStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StudId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstFollowUp" Member="MstFollowUps">
    <Type Name="MstFollowUp">
      <Column Name="FollowId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnqId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FollowupDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FollowupStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Outcome" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NextFollowup" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AssignTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_MerchandiseOrder" Member="Tbl_MerchandiseOrders">
    <Type Name="Tbl_MerchandiseOrder">
      <Column Name="ItemSFId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Merchandise" Member="Tbl_Merchandises">
    <Type Name="Tbl_Merchandise">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitCost" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_CourseFeeDetail" Member="Tbl_CourseFeeDetails">
    <Type Name="Tbl_CourseFeeDetail">
      <Column Name="FeeDId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdultFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegnFee" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Renewal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sessn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hrs" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Assessment" Member="Tbl_Assessments">
    <Type Name="Tbl_Assessment">
      <Column Name="AssessId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrainerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AssessDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Grade" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AssessorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Remarks" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_StudFee" Member="Tbl_StudFees">
    <Type Name="Tbl_StudFee">
      <Column Name="SFeeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sessn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SesnStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hrs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AdmissionNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Vw_StudFeeDet" Member="Vw_StudFeeDets">
    <Type Name="Vw_StudFeeDet">
      <Column Name="SFeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sessn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hrs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudName" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Page" Member="Tbl_Pages">
    <Type Name="Tbl_Page">
      <Column Name="PageID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ActionValue" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ParentPageID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ActionUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ShowInMenu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowInPrivilege" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UIData" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Tbl_Page_Tbl_Privilege" Member="Tbl_Privileges" ThisKey="PageID" OtherKey="PageID" Type="Tbl_Privilege" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Privilege" Member="Tbl_Privileges">
    <Type Name="Tbl_Privilege">
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PageID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ActionValue" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CrtBy" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CrtOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CrtNode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdBy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UpdOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tbl_Page_Tbl_Privilege" Member="Tbl_Page" ThisKey="PageID" OtherKey="PageID" Type="Tbl_Page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_Role" Member="Tbl_Roles">
    <Type Name="Tbl_Role">
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CrtBy" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CrtOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CrtNode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UpdBy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UpdOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdNode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Tbl_Role_Tbl_AppUser" Member="Tbl_AppUsers" ThisKey="RoleID" OtherKey="RoleID" Type="Tbl_AppUser" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_LoginAudit" Member="Tbl_LoginAudits">
    <Type Name="Tbl_LoginAudit">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoginTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LoginStatus" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="LoginNode" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="LogoutTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tbl_AppUsers" Member="Tbl_AppUsers">
    <Type Name="Tbl_AppUser">
      <Column Name="UserID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginID" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmailID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="InvalidLoginCount" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="LastSuccessfulLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLoginAttempt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CrtBy" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CrtOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CrtNode" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UpdBy" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="UpdOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdNode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EmpID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Tbl_Role_Tbl_AppUser" Member="Tbl_Role" ThisKey="RoleID" OtherKey="RoleID" Type="Tbl_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MstAttendance" Member="MstAttendances">
    <Type Name="MstAttendance">
      <Column Name="AttendId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AttendDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OutTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.GetRecordUpdateDetails" Method="GetRecordUpdateDetails">
    <Parameter Name="tablename" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="condition" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_GetUserLogin" Method="PR_GetUserLogin">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IPAddress" Parameter="iPAddress" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IPCode" Parameter="iPCode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="UTCoffset" Parameter="uTCoffset" Type="System.Decimal" DbType="Decimal(7,4)" />
    <ElementType Name="PR_GetUserLoginResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(201) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetLocations" Method="PR_GetLocations">
    <ElementType Name="PR_GetLocationsResult">
      <Column Name="ViewId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LocAddress" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetLocById" Method="PR_GetLocById">
    <Parameter Name="LocId" Parameter="locId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_GetLocByIdResult">
      <Column Name="LocId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LocAddress" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetMenuList" Method="PR_GetMenuList">
    <Parameter Name="ParentId" Parameter="parentId" Type="System.Int32" DbType="Int" />
    <Parameter Name="GroupId" Parameter="groupId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_GetMenuListResult">
      <Column Name="MenuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MenuText" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="NavigateUrl" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ViewProcedure" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RecordsUrl" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdentityColumn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TableName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetStudById" Method="PR_GetStudById">
    <Parameter Name="StudId" Parameter="studId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_GetStudByIdResult">
      <Column Name="ViewId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="BloodGroup" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="StudentId" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UniqueId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_Student" Method="PR_Student">
    <ElementType Name="PR_StudentResult">
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_Schedules" Method="PR_Schedules">
    <ElementType Name="PR_SchedulesResult">
      <Column Name="TSchdlId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FromTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ToTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_User" Method="PR_User">
    <ElementType Name="PR_UserResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetFollowupDet" Method="PR_GetFollowupDet">
    <ElementType Name="PR_GetFollowupDetResult">
      <Column Name="EnqId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EnqStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FollowupDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FollowupStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Outcome" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="NextFollowup" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FollowId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetLeads" Method="PR_GetLeads">
    <ElementType Name="PR_GetLeadsResult">
      <Column Name="EnqId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SourceName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EnqType" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="EnqDate" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EnqStatus" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetStudents" Method="PR_GetStudents">
    <ElementType Name="PR_GetStudentsResult">
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UAEId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Imagepath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetStudentsbyId" Method="PR_GetStudentsbyId">
    <Parameter Name="StuId" Parameter="stuId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_GetStudentsbyIdResult">
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Course" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UAEId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Expdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Imagepath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetItems" Method="PR_GetItems">
    <ElementType Name="PR_GetItemsResult">
      <Column Name="ItemSFId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemQty" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmt" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UnitCost" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetFees" Method="PR_GetFees">
    <Parameter Name="StuId" Parameter="stuId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_GetFeesResult">
      <Column Name="SFeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sessn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hrs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudName" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetFeeById" Method="PR_GetFeeById">
    <Parameter Name="FeeId" Parameter="feeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_GetFeeByIdResult">
      <Column Name="SFeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RegAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AAmt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sessn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hrs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudName" Type="System.String" DbType="VarChar(201)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_LoginAudit" Method="PR_LoginAudit">
    <Parameter Name="pUserID" Type="System.Int32" DbType="Int" />
    <Parameter Name="pLoginStatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pLoginNode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pAuditID" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <ElementType Name="PR_LoginAuditResult">
      <Column Name="AuditID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.FN_PrivilegeGet" Method="FN_PrivilegeGet" IsComposable="true">
    <Parameter Name="pActionValue" Type="System.Byte" DbType="TinyInt" />
    <ElementType Name="FN_PrivilegeGetResult">
      <Column Name="CanModify" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_UserPrivilegeGet" Method="PR_UserPrivilegeGet">
    <Parameter Name="pUserID" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_UserPrivilegeGetResult">
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="PageID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ActionValue" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ActionUrl" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ParentPageID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UIData" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CanModify" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowInMenu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowInPrivilege" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DisplayOrder" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_UserPswdUpdate" Method="PR_UserPswdUpdate">
    <Parameter Name="pUserID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pCrtBy" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pCrtNode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pPassword" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="pPasswordSalt" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_UserSearch" Method="PR_UserSearch">
    <Parameter Name="pUserID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pLoginID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pRoleID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pFullName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pEmailID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pIsActive" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="PR_UserSearchResult">
      <Column Name="UserID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="LoginID" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginOn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EmpId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_UserSave" Method="PR_UserSave">
    <Parameter Name="pUserID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pLoginID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pRoleID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pFullName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pEmailID" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="pIsActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="pCrtBy" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pCrtNode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pPassword" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="pPasswordSalt" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="pEmpId" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_UserSaveResult">
      <Column Name="ResponseCode" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_RoleGetDetail" Method="PR_RoleGetDetail">
    <Parameter Name="pRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_RoleGetDetailResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PageID" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PageDescription" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ActionValue" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CanModify" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CanView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EntCanModify" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EntCanView" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowInPrivilege" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ShowInMenu" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ParentPageID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_RoleSearch" Method="PR_RoleSearch">
    <Parameter Name="pDescription" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="pRoleID" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_RoleSearchResult">
      <Column Name="RoleID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_RoleSave" Method="PR_RoleSave">
    <Parameter Name="pDescription" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="pIsActive" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="pCrtBy" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pCrtNode" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="pRoleID" Type="System.Int16" DbType="SmallInt" />
    <Parameter Name="pRoles" Type="System.String" DbType="VarChar(MAX)" />
    <ElementType Name="PR_RoleSaveResult">
      <Column Name="ResponseCode" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetAttendees" Method="PR_GetAttendees">
    <ElementType Name="PR_GetAttendeesResult">
      <Column Name="AttendId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AttendDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="InTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OutTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetTrainer" Method="PR_GetTrainer">
    <ElementType Name="PR_GetTrainerResult">
      <Column Name="TrainerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetSchedules" Method="PR_GetSchedules">
    <ElementType Name="PR_GetSchedulesResult">
      <Column Name="TSchdlId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScheduleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClassDays" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FromTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ToTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Activity" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Trainer" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_GetSchedule" Method="PR_GetSchedule">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="PR_GetScheduleResult">
      <Column Name="ScheduleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="coursename" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="LocName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FromDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FromTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ToTime" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>